version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'semaphore'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    hostname: mysql
    expose:
      - 3306
    volumes:
      - /opt/data/mysql/:/var/lib/mysql

  semaphore:
    image: sig9/semaphore:2.4.1
    depends_on:
      - mysql
    ports:
      - 3000:3000
    links:
      - mysql:mysql
    volumes:
      - /opt/data/semaphore/:/opt/semaphore
