mysql:
  image: mysql
  environment:
    MYSQL_DATABASE: 'semaphore'
    MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  hostname: mysql
  expose:
    - 3306
  volumes:
    - /opt/data/mysql/:/var/lib/mysql

semaphore:
  image: sig9/semaphore:latest
  expose:
    - 3000
  ports:
    - 3000:3000
  links:
    - mysql:mysql
#  volumes:
#    - /opt/data/semaphore/:/opt/data/semaphore

gitbucket:
  image: sig9/gitbucket:latest
  expose:
    - 8080
    - 29418
  ports:
    - 8080:8080
    - 29418:29418
  volumes:
    - /opt/data/gitbucket:/gitbucket
