version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'semaphore'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    hostname: mysql
    expose:
      - 3306
    volumes:
      - /opt/data/mysql/:/var/lib/mysql

  semaphore:
    image: sig9/semaphore:latest
    depends_on:
      - mysql
    ports:
      - 3000:3000
    links:
      - mysql:mysql
    volumes:
      - /opt/data/semaphore/:/opt/semaphore

  gitbucket:
    image: sig9/gitbucket:latest
    ports:
      - 8080:8080
      - 29418:29418
    volumes:
      - /opt/data/gitbucket:/gitbucket
